# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('lat', models.FloatField(default=0)),
                ('long', models.FloatField(default=0)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='image/place')),
                ('description', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('startAt', models.DateTimeField()),
                ('joinCount', models.IntegerField(default=0)),
            ],
        ),
    ]
