# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-23 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import service.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lat', models.FloatField(default=0)),
                ('long', models.FloatField(default=0)),
                ('image', models.ImageField(blank=True, default='image/hotel/default.jpg', null=True, upload_to=service.models.PathAndRename('image/hotel'))),
                ('star', models.FloatField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('openAt', models.TimeField(default='00:00')),
                ('closeAt', models.TimeField(default='00:00')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'service_category',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='service.ServiceCategory'),
        ),
    ]
