# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-23 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import service.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='address',
            field=models.TextField(blank=True, default='Không xác định', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, default='image/hotel/default.jpg', null=True, upload_to=service.models.PathAndRename('image/service')),
        ),
    ]
