# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-17 13:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20171215_0741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='closeAt',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 12, 17, 13, 24, 23, 171955, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='openAt',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='services',
            field=models.ManyToManyField(related_name='restaurants', to='restaurant.Service'),
        ),
    ]
