# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-17 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20171214_1747'),
        ('restaurant', '0003_auto_20171217_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='customer.Customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='closeAt',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='openAt',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
