# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20180107_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, default='image/restaurant/default.jpg', null=True, upload_to='image/restaurant'),
        ),
    ]
