# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20180109_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='closeAt',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='openAt',
            field=models.TimeField(default='00:00'),
        ),
    ]
