# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_auto_20180109_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='restaurants', to='restaurant.Service'),
        ),
    ]
