# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/hotel'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='long',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='star',
            field=models.FloatField(default=0),
        ),
    ]
