# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20171214_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='services',
            field=models.ManyToManyField(related_name='hotels', to='hotel.Service'),
        ),
    ]
