# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-17 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20171216_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='closeAt',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='openAt',
            field=models.TimeField(auto_now=True),
        ),
    ]
