# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-17 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20171214_1747'),
        ('hotel', '0004_auto_20171217_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='customer.Customer'),
            preserve_default=False,
        ),
    ]
