# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-17 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_hotel_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='closeAt',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='openAt',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
