# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-07 10:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20171214_1747'),
        ('hotel', '0006_auto_20171217_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedHotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('bookedAt', models.DateField(blank=True, default=datetime.datetime.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_hotel_meta', to='customer.Customer')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_customer_meta', to='hotel.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteHotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_hotel_meta', to='customer.Customer')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_customer_meta', to='hotel.Hotel')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='favoritehotel',
            unique_together=set([('customer', 'hotel')]),
        ),
    ]
