# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_auto_20180109_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='closeAt',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='openAt',
            field=models.TimeField(default='00:00'),
        ),
    ]
